server:
  port: 0

#eureka:
 # client:
  #  serviceUrl:
   #   defaultZone: http://localhost:8761/eureka
 

 
spring:
  datasource:
    url: jdbc:mysql://project-management.cmbnvqzejn0j.us-east-2.rds.amazonaws.com:3306/project_management?useSSL=false
    username: admin
    password: PassworD
    
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    show-sql: true
  application:
    name: project-management
  cloud:
    config:
      uri: http://localhost:8765/
        
     
