server:
  port: 0

#eureka:
 # client:
  #  serviceUrl:
   #   defaultZone: http://localhost:8761/eureka
 

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_management
    username: root
    password: pass@word1 

  application:
    name: project-management
  cloud:
    config:
      uri: http://localhost:8765/
        
     
  #jpa:
   # hibernate:
    #  ddl-auto: create
    show-sql: true