server:
  port: 0
 
spring:
  datasource:
    url: jdbc:mysql://project-management.cmbnvqzejn0j.us-east-2.rds.amazonaws.com:3306/project_management?useSSL=false
    username: admin
    password: PassworD
    
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    show-sql: true
  application:
    name: admin-view
  cloud:
    config:
      uri: http://localhost:8765/
  data:
    mongodb:
       uri: mongodb+srv://user1:zVcOiZnu2OByw56x@cluster0-egasi.mongodb.net/ProjectManagement?retryWrites=true&w=majority
      
      #uri: mongodb://127.0.0.1:27017/ProjectDescStakeDb
    
      
 # application:
  #  name: project-management
  #zipkin:
   # base-url: http://localhost:9411/
 # cloud:
  #  config:
   #   url: http=//localhost:8765/
  